"""Logradouros e bairros de Morrinhos.

Gerado do Cadastro de Logradouros dos Correios (DNE) fornecido pela
serventia. NÃO EDITE À MÃO: rode `py tools/gera_logradouros.py` com a
lista nova quando ela for atualizada.

Só constam os nomes que mudam com o acento — a CAIXA grava tudo sem
acento, e é essa conversão que a ferramenta precisa fazer sem chutar.
"""

# chave: nome sem acento e em caixa alta, como a CAIXA grava
LOGRADOUROS = {
    '1': '1',
    '10': '10',
    '100': '100',
    '101': '101',
    '101B': '101B',
    '102': '102',
    '102A': '102A',
    '103': '103',
    '105': '105',
    '107': '107',
    '109': '109',
    '11': '11',
    '111': '111',
    '113': '113',
    '11A': '11A',
    '12': '12',
    '13': '13',
    '13 DE MAIO': '13 de Maio',
    '14': '14',
    '15': '15',
    '16': '16',
    '16A': '16A',
    '17': '17',
    '17A': '17A',
    '18': '18',
    '18A': '18A',
    '18B': '18B',
    '18C': '18C',
    '19': '19',
    '19A': '19A',
    '1A': '1A',
    '2': '2',
    '2 RAMAL A': '2 Ramal A',
    '2 RAMAL B': '2 Ramal B',
    '20': '20',
    '202A': '202A',
    '203': '203',
    '203A': '203A',
    '204': '204',
    '204A': '204A',
    '204B': '204B',
    '205': '205',
    '205A': '205A',
    '205B': '205B',
    '206': '206',
    '207': '207',
    '208': '208',
    '209': '209',
    '20A': '20A',
    '21': '21',
    '211': '211',
    '212': '212',
    '212A': '212A',
    '212B': '212B',
    '213': '213',
    '21A': '21A',
    '22A': '22A',
    '22B': '22B',
    '24': '24',
    '25': '25',
    '25 DE MAIO': '25 de Maio',
    '26': '26',
    '27': '27',
    '28': '28',
    '29': '29',
    '2A': '2A',
    '2B': '2B',
    '2C': '2C',
    '2D': '2D',
    '3': '3',
    '30 DE AGOSTO': '30 de Agosto',
    '33': '33',
    '34': '34',
    '35': '35',
    '3A': '3A',
    '4': '4',
    '4A': '4A',
    '4B': '4B',
    '4C': '4C',
    '4D': '4D',
    '5': '5',
    '6': '6',
    '6A': '6A',
    '6B': '6B',
    '7': '7',
    '7 DE SETEMBRO': '7 de Setembro',
    '7 DE SETEMBRO RAMAL A': '7 de Setembro Ramal A',
    '7 DE SETEMBRO RAMAL B': '7 de Setembro Ramal B',
    '8': '8',
    '8 DE AGOSTO': '8 de Agosto',
    '9': '9',
    'A': 'A',
    'A SALVADOR COSTA': 'A Salvador Costa',
    'ACAI': 'Açaí',
    'ADELINO RIBEIRO DA SILVA': 'Adelino Ribeiro da Silva',
    'AGENOR VICENTE DA SILVA': 'Agenor Vicente da Silva',
    'ALAGOAS': 'Alagoas',
    'ALBERTO XAVIER': 'Alberto Xavier',
    'ALEXANDRIA': 'Alexandria',
    'AMAZONAS': 'Amazonas',
    'ANAIDES MARIA DO CARMO OLIVEIRA': 'Anaídes Maria do Carmo Oliveira',
    'ANCONA': 'Ancona',
    'ANGICO': 'Angico',
    'ANTONIO ALVES RABELO': 'Antônio Alves Rabelo',
    'ANTONIO CASCAO': 'Antônio Cascão',
    'ANTONIO L GOMES': 'Antonio L Gomes',
    'ANTONIO ROSA RIBEIRO FALCAO': 'Antônio Rosa Ribeiro Falcão',
    'ANTONIO TITO': 'Antônio Tito',
    'AREZZO': 'Arezzo',
    'ARGOS': 'Argos',
    'ARMIDIO FELIPE SANTIAGO': 'Armídio Felipe Santiago',
    'AROEIRA': 'Aroeira',
    'B': 'B',
    'B-1': 'B-1',
    'B-1A': 'B-1A',
    'BACURI': 'Bacuri',
    'BARAO DO RIO BRANCO': 'Barão do Rio Branco',
    'BARI': 'Bari',
    'BARU': 'Barú',
    'BERALDINO JESUINO DE SOUZA': 'Beraldino Jesuíno de Souza',
    'BERGAMO': 'Bérgamo',
    'BOLONHA': 'Bolonha',
    'BRESCIA': 'Bréscia',
    'BRINDISI': 'Brindisi',
    'BURITI': 'Buriti',
    'BV-1': 'BV-1',
    'BV-10': 'BV-10',
    'BV-11': 'BV-11',
    'BV-11A': 'BV-11A',
    'BV-12': 'BV-12',
    'BV-13': 'BV-13',
    'BV-14': 'BV-14',
    'BV-14A': 'BV-14A',
    'BV-1A': 'BV-1A',
    'BV-1B': 'BV-1B',
    'BV-2': 'BV-2',
    'BV-2B': 'BV-2B',
    'BV-3': 'BV-3',
    'BV-3B': 'BV-3B',
    'BV-4': 'BV-4',
    'BV-5': 'BV-5',
    'BV-6': 'BV-6',
    'BV-7': 'BV-7',
    'BV-8': 'BV-8',
    'BV-9': 'BV-9',
    'C': 'C',
    'C-1': 'C-1',
    'CAMPONESA': 'Camponesa',
    'CARAIBA': 'Caraíba',
    'CARMINDO COELHO G DE ALMEIDA': 'Carmindo Coelho G de Almeida',
    'CASIMIRO LUIZ FERREIRA': 'Casimiro Luiz Ferreira',
    'CASTRO ALVES': 'Castro Alves',
    'CEARA': 'Ceará',
    'CEDRO': 'Cedro',
    'CENTRAL': 'Central',
    'CLOVIS CARNEIRO': 'Clovis Carneiro',
    'CORONEL BENTO GODOY': 'Coronel Bento Godoy',
    'CORONEL FERNANDO BARBOSA': 'Coronel Fernando Barbosa',
    'CORONEL JOAO LOPES ZEDES': 'Coronel João Lopes Zedes',
    'CORONEL PEDRO NUNES': 'Coronel Pedro Nunes',
    'COUTO DE MAGALHAES': 'Couto de Magalhães',
    'CP-1': 'CP-1',
    'CP-10': 'CP-10',
    'CP-11': 'CP-11',
    'CP-2': 'CP-2',
    'CP-3': 'CP-3',
    'CP-3A': 'CP-3A',
    'CP-4': 'CP-4',
    'CP-5': 'CP-5',
    'CP-6': 'CP-6',
    'CP-6A': 'CP-6A',
    'CP-7': 'CP-7',
    'CP-7A': 'CP-7A',
    'CP-8': 'CP-8',
    'CP-9': 'CP-9',
    'CR-1': 'CR-1',
    'CR-10': 'CR-10',
    'CR-11': 'CR-11',
    'CR-2': 'CR-2',
    'CR-3': 'CR-3',
    'CR-4': 'CR-4',
    'CR-5': 'CR-5',
    'CR-6': 'CR-6',
    'CR-7': 'CR-7',
    'CR-8': 'CR-8',
    'CR-9': 'CR-9',
    'CREMONA': 'Cremona',
    'CRETA': 'Creta',
    'D': 'D',
    'DA LAVANDERIA': 'da Lavanderia',
    'DA MANGUEIRA': 'da Mangueira',
    'DA PITOMBEIRA': 'da Pitombeira',
    'DANTE COSTA': 'Dante Costa',
    'DARCY CHAVES': 'Darcy Chaves',
    'DAS ACACIAS': 'das Acácias',
    'DAS AZALEIAS': 'das Azaléias',
    'DAS BANANEIRAS': 'das Bananeiras',
    'DAS BEGONIAS': 'das Begônias',
    'DAS BROMELIAS': 'das Bromélias',
    'DAS CAMELIAS': 'das Camélias',
    'DAS FLORES': 'das Flores',
    'DAS GOIABEIRAS': 'das Goiabeiras',
    'DAS HORTENCIAS': 'das Hortências',
    'DAS JABUTICABEIRAS': 'das Jabuticabeiras',
    'DAS LARANJEIRAS': 'das Laranjeiras',
    'DAS LIMEIRAS': 'das Limeiras',
    'DAS MARGARIDAS': 'das Margaridas',
    'DAS ORQUIDEAS': 'das Orquídeas',
    'DAS PALMAS': 'das Palmas',
    'DAS PALMEIRAS': 'das Palmeiras',
    'DAS ROSAS': 'das Rosas',
    'DAS VIDEIRAS': 'das Videiras',
    'DAS VIOLETAS': 'das Violetas',
    'DAVI TRONCOSO CARRERA': 'Davi Troncoso Carrera',
    'DC-1': 'DC-1',
    'DC-10': 'DC-10',
    'DC-2': 'DC-2',
    'DC-3': 'DC-3',
    'DC-4': 'DC-4',
    'DC-5': 'DC-5',
    'DC-6': 'DC-6',
    'DC-7': 'DC-7',
    'DC-8': 'DC-8',
    'DC-9': 'DC-9',
    'DE ACESSO': 'de Acesso',
    'DELFINO CURADO': 'Delfino Curado',
    'DIAS COELHO': 'Dias Coelho',
    'DIMAS VITOR SOUZA': 'Dimas Vítor Souza',
    'DIVINO BIDON': 'Divino Bidon',
    'DO BOIADEIRO': 'do Boiadeiro',
    'DO CAFE': 'do Café',
    'DO CAJU': 'do Caju',
    'DO CORETO': 'do Coreto',
    'DOM PEDRO II': 'Dom Pedro II',
    'DOMINGOS RICARDO DE SOUZA': 'Domingos Ricardo de Souza',
    'DONA FIICA': 'Dona Fiica',
    'DOS GIRASSOIS': 'dos Girassóis',
    'DOS IPES': 'dos Ipês',
    'DOS JASMINS': 'dos Jasmins',
    'DOS LIRIOS': 'dos Lírios',
    'DOS TRABALHADORES': 'dos Trabalhadores',
    'DOUTOR ALVARO TEIXEIRA DE CAMARGO': 'Doutor Álvaro Teixeira de Camargo',
    'DOUTOR ANTONIO CARNEIRO': 'Doutor Antonio Carneiro',
    'DOUTOR ANTONIO J MELO': 'Doutor Antônio J Melo',
    'DOUTOR EDUVAL PEREIRA MAIA': 'Doutor Eduval Pereira Maia',
    'DOUTOR GUILHERME XAVIER ALMEIDA': 'Doutor Guilherme Xavier Almeida',
    'DOUTOR GUMERCINDO OTERO': 'Doutor Gumercindo Otero',
    'DOUTOR JAIR DE FREITAS': 'Doutor Jair de Freitas',
    'DOUTOR PEDRO NUNES': 'Doutor Pedro Nunes',
    'DOUTOR RAUL NUNES': 'Doutor Raul Nunes',
    'DOUTOR SILVIO DE MELO': 'Doutor Sílvio de Melo',
    'E': 'E',
    'ELI RIBEIRO DIAS': 'Eli Ribeiro Dias',
    'ELMO CARNEIRO': 'Elmo Carneiro',
    'ENGENHEIRO FLAVIO CASCAO': 'Engenheiro Flávio Cascão',
    'ERMELINDA GONZAGA DE AQUINO': 'Ermelinda Gonzaga de Aquino',
    'ESPARTA': 'Esparta',
    'F': 'F',
    'FC-1': 'FC-1',
    'FC-2': 'FC-2',
    'FC-3': 'FC-3',
    'FC-4': 'FC-4',
    'FC-5': 'FC-5',
    'FC-6': 'FC-6',
    'FC-8': 'FC-8',
    'FELICIDADE ESTRELA DE GODOY': 'Felicidade Estrela de Godoy',
    'FERRARA': 'Ferrara',
    'FIICA MARCAL': 'Fiica Marçal',
    'FIRMO ANTONIO DE FREITAS': 'Firmo Antônio de Freitas',
    'FLAMBOYANT': 'Flamboyant',
    'FLORENCA': 'Florença',
    'FORTALEZA': 'Fortaleza',
    'FRANCISCO ROSA CAMPOS': 'Francisco Rosa Campos',
    'FRANCISCO VINUTO ALVES': 'Francisco Vinuto Alves',
    'G': 'G',
    'GA-1': 'GA-1',
    'GA-10': 'GA-10',
    'GA-11': 'GA-11',
    'GA-12': 'GA-12',
    'GA-13': 'GA-13',
    'GA-14': 'GA-14',
    'GA-15': 'GA-15',
    'GA-15A': 'GA-15A',
    'GA-16': 'GA-16',
    'GA-2': 'GA-2',
    'GA-3': 'GA-3',
    'GA-4': 'GA-4',
    'GA-4A': 'GA-4A',
    'GA-5': 'GA-5',
    'GA-6': 'GA-6',
    'GA-7': 'GA-7',
    'GA-8': 'GA-8',
    'GA-9': 'GA-9',
    'GASPAR MARTINS DE OLIVEIRA': 'Gaspar Martins de Oliveira',
    'GENOVA': 'Génova',
    'GENOVEVA REZENDE CARNEIRO': 'Genoveva Rezende Carneiro',
    'GERALDINO DE FREITAS': 'Geraldino de Freitas',
    'GERALDO JOSE DE SOUZA': 'Geraldo José de Souza',
    'GERALDO SANTANA': 'Geraldo Santana',
    'GERSON RIBEIRO': 'Gerson Ribeiro',
    'GILDA D FONTES': 'Gilda D Fontes',
    'GOIAS': 'Goiás',
    'GUMERCINDO INOCENCIO DE OLIVEIRA': 'Gumercindo Inocêncio de Oliveira',
    'GUSTAVO EMILIO FELTER': 'Gustavo Emílio Felter',
    'H': 'H',
    'H-1': 'H-1',
    'H-10': 'H-10',
    'H-11': 'H-11',
    'H-13': 'H-13',
    'H-15': 'H-15',
    'H-2': 'H-2',
    'H-3': 'H-3',
    'H-4': 'H-4',
    'H-5': 'H-5',
    'H-6': 'H-6',
    'H-7': 'H-7',
    'H-8': 'H-8',
    'H-9': 'H-9',
    'HELENIENE CANDIDO DOS SANTOS': 'Heleniene Cândido dos Santos',
    'HERCILIO GOMES DE MELO': 'Hercílio Gomes de Melo',
    'HF': 'HF',
    'HORIZONTE': 'Horizonte',
    'HP': 'HP',
    'I': 'I',
    'IDELMA CARNEIRO': 'Idelma Carneiro',
    'II': 'II',
    'III': 'III',
    'INACIO CORREA': 'Inácio Correa',
    'INDEPENDENTE': 'Independente',
    'IPE': 'Ipê',
    'IRENEA DE FREITAS CHAVES': 'Irenéa de Freitas Chaves',
    'ISABELA CANDIDO': 'Isabela Cândido',
    'ISOLINA NORATO DE JESUS': 'Isolina Norato de Jesus',
    'ITAMAR BERNARDINO DE SOUZA': 'Itamar Bernardino de Souza',
    'IVANOLPH MESQUITA': 'Ivanolph Mesquita',
    'J': 'J',
    'J1': 'J1',
    'J2': 'J2',
    'J3': 'J3',
    'J4': 'J4',
    'JACARANDA': 'Jacarandá',
    'JAIME VILELA': 'Jaime Vilela',
    'JATOBA': 'Jatobá',
    'JC-I': 'JC-I',
    'JC-II': 'JC-II',
    'JC-III': 'JC-III',
    'JC-IV': 'JC-IV',
    'JC-V': 'JC-V',
    'JC-VI': 'JC-VI',
    'JERIVA': 'Jerivá',
    'JG-I': 'JG-I',
    'JG-II': 'JG-II',
    'JG-III': 'JG-III',
    'JG-IV': 'JG-IV',
    'JG-V': 'JG-V',
    'JG-VI': 'JG-VI',
    'JG-VII': 'JG-VII',
    'JG-VIII': 'JG-VIII',
    'JG-X': 'JG-X',
    'JJ 02': 'JJ 02',
    'JJ 03': 'JJ 03',
    'JJ 04': 'JJ 04',
    'JJ 05': 'JJ 05',
    'JJ 06': 'JJ 06',
    'JJ 07': 'JJ 07',
    'JJ 08': 'JJ 08',
    'JJ 09': 'JJ 09',
    'JJ 10': 'JJ 10',
    'JJ 11': 'JJ 11',
    'JOAO BARBOSA DE SOUZA': 'João Barbosa de Souza',
    'JOAO FERREIRA MACEDO': 'João Ferreira Macedo',
    'JOAO JULIO DE OLIVEIRA': 'João Júlio de Oliveira',
    'JOAO PINTO DE OLIVEIRA': 'João Pinto de Oliveira',
    'JOAQUIM ALVES COUTINHO': 'Joaquim Alves Coutinho',
    'JOAQUIM DINIZ': 'Joaquim Diniz',
    'JOAQUIM GODOY': 'Joaquim Godoy',
    'JOAQUIM LUIZ CASCAO': 'Joaquim Luiz Cascão',
    'JOAQUIM QUITERIO': 'Joaquim Quitério',
    'JONAS INOCENCIO DE OLIVEIRA': 'Jonas Inocêncio de Oliveira',
    'JONAS ROMANO': 'Jonas Romano',
    'JORDELINA DE FREITAS': 'Jordelina de Freitas',
    'JORGE ROMANO JUNIOR': 'Jorge Romano Júnior',
    'JORIVE GUARANI COSTA': 'Jorivê Guarani Costa',
    'JOSE DANIEL DA SILVA': 'José Daniel da Silva',
    'JOSE DIVINO PRUDENTE': 'José Divino Prudente',
    'JOSE ELIAS BORGES': 'José Elias Borges',
    'JOSE GOMES VEADO': 'José Gomes Veado',
    'JOSE NELSON': 'José Nelson',
    'JOSINA BARBOSA DE FREITAS': 'Josina Barbosa de Freitas',
    'JOVIANO ANTONIO FERNANDES': 'Joviano Antonio Fernandes',
    'JUSCELINO KUBITSCHEK': 'Juscelino Kubitschek',
    'K': 'K',
    'KM': 'KM',
    'L': 'L',
    'LEILA REGINA': 'Leila Regina',
    'LIGURIA': 'Ligúria',
    'LIONS': 'Lions',
    'LIVORNO': 'Livorno',
    'LOGRADOURO CEP BAIRRO': 'Logradouro             CEP                              Bairro',
    'LOIR CARNEIRO DE CASTRO': 'Loir Carneiro de Castro',
    'LOMBARDIA': 'Lombardia',
    'M': 'M',
    'MAESTRO VICENTE JOSE VIEIRA': 'Maestro Vicente José Vieira',
    'MAJOR EVARISTO FRAUZINO': 'Major Evaristo Frauzino',
    'MAJOR LIMIRIO': 'Major Limírio',
    'MANOEL DE FREITAS': 'Manoel de Freitas',
    'MARIA ALVES PEREIRA': 'Maria Alves Pereira',
    'MARIA AMABINI DE MORAES': 'Maria Amabini de Moraes',
    'MARIA EDUARDA RODRIGUES': 'Maria Eduarda Rodrigues',
    'MARIA FERREIRA DE SOUZA': 'Maria Ferreira de Souza',
    'MARIA ROSA': 'Maria Rosa',
    'MARIQUINHA DE FREITAS': 'Mariquinha de Freitas',
    'MATO GROSSO': 'Mato Grosso',
    'MELANIAS VIEIRA DE MELO': 'Melanias Vieira de Melo',
    'MILAO': 'Milão',
    'MINAS GERAIS': 'Minas Gerais',
    'MINERVINO QUINTINO MARTINS': 'Minervino Quintino Martins',
    'MOGNO': 'Mogno',
    'MORRO MANOEL MENDONCA': 'Morro Manoel Mendonça',
    'MV-1': 'MV-1',
    'MV-10': 'MV-10',
    'MV-11': 'MV-11',
    'MV-12': 'MV-12',
    'MV-13': 'MV-13',
    'MV-14': 'MV-14',
    'MV-15': 'MV-15',
    'MV-16': 'MV-16',
    'MV-17': 'MV-17',
    'MV-18': 'MV-18',
    'MV-19': 'MV-19',
    'MV-1A': 'MV-1A',
    'MV-2': 'MV-2',
    'MV-20': 'MV-20',
    'MV-21': 'MV-21',
    'MV-3': 'MV-3',
    'MV-4': 'MV-4',
    'MV-5': 'MV-5',
    'MV-6': 'MV-6',
    'MV-7': 'MV-7',
    'MV-8': 'MV-8',
    'MV-9': 'MV-9',
    'N': 'N',
    'NAPOLIS': 'Nápolis',
    'NOE JOSE PEREIRA': 'Noé José Pereira',
    'NORMA GRACE SIMIEMA': 'Norma Grace Simiema',
    'NOVARA': 'Novara',
    'OSMIRA CARNEIRO': 'Osmira Carneiro',
    'OSVALDO R DE SOUZA': 'Osvaldo R de Souza',
    'OVIDIO JOSE DOS SANTOS': 'Ovidio José dos Santos',
    'P': 'P',
    'PADRE SAMUEL GEORGE': 'Padre Samuel George',
    'PADUA': 'Pádua',
    'PAINEIRA': 'Paineira',
    'PARA': 'Pará',
    'PARAIBA': 'Paraíba',
    'PARANA': 'Paraná',
    'PARMA': 'Parma',
    'PASSAGEM DE PEDESTRE': 'Passagem de Pedestre',
    'PASTOR BELINO GONCALVES DAMACENO': 'Pastor Belino Gonçalves Damaceno',
    'PAULO DE SOUZA': 'Paulo de Souza',
    'PAVIA': 'Pavia',
    'PEDRO BRAGA': 'Pedro Braga',
    'PEQUI': 'Pequi',
    'PERIMETRAL': 'Perimetral',
    'PERNAMBUCO': 'Pernambuco',
    'PEROBA ROSA': 'Peroba Rosa',
    'PERUCIA': 'Perucia',
    'PIAUI': 'Piauí',
    'POR ORDEM ALFABETICA CEP BAIRRO': 'Por ordem Alfabética                       CEP                                  Bairro',
    'PORTO ALEGRE': 'Porto Alegre',
    'POVOADO DE RANCHO ALEGRE': 'Povoado de Rancho Alegre',
    'PREFEITO ANTONIO DE CASTRO ROSA': 'Prefeito Antônio de Castro Rosa',
    'PREFEITO MANOEL DE FREITAS': 'Prefeito Manoel de Freitas',
    'PROFESSOR FELICIO CHAVES': 'Professor Felício Chaves',
    'PROFESSOR FRAUZINO SOBRINHO': 'Professor Frauzino Sobrinho',
    'PROFESSOR JOSE CANDIDO': 'Professor José Cândido',
    'PROFESSOR JOSE DO NASCIMENTO': 'Professor José do Nascimento',
    'PROFESSOR MANOEL LEMOS DE MENDONCA': 'Professor Manoel Lemos de Mendonça',
    'PROFESSORA ZILDA DINIZ FONTES': 'Professora Zilda Diniz Fontes',
    'QUERIDINHA': 'Queridinha',
    'RAIMUNDO N RIBEIRO': 'Raimundo N Ribeiro',
    'RAVENA': 'Ravena',
    'RDO 1': 'RDO 1',
    'RDO 2': 'RDO 2',
    'RDO 3': 'RDO 3',
    'RDO 4': 'RDO 4',
    'RDO 5': 'RDO 5',
    'RDO 6': 'RDO 6',
    'RDO 7': 'RDO 7',
    'REGIO': 'Regio',
    'REGIO 2': 'Regio 2',
    'REVERENDO ARCHIBALD TIPPLE': 'Reverendo Archibald Tipple',
    'RI-1': 'RI-1',
    'RI-1A': 'RI-1A',
    'RI-2': 'RI-2',
    'RI-2A': 'RI-2A',
    'RI-3': 'RI-3',
    'RI-4': 'RI-4',
    'RI-5': 'RI-5',
    'RI-6': 'RI-6',
    'RI-7': 'RI-7',
    'RI-8': 'RI-8',
    'RI-9': 'RI-9',
    'RIO DE JANEIRO': 'Rio de Janeiro',
    'RIO GRANDE DO SUL': 'Rio Grande do Sul',
    'RODRIGO FREITAS DE MORAES': 'Rodrigo Freitas de Moraes',
    'ROMA': 'Roma',
    'ROSA CASCAO': 'Rosa Cascão',
    'ROSELI CARNEIRO DE CASTRO': 'Roseli Carneiro de Castro',
    'RURAL': 'Rural',
    'SALERMO': 'Salermo',
    'SANTO AGOSTINHO': 'Santo Agostinho',
    'SANTORINI': 'Santorini',
    'SAO PAULO': 'São Paulo',
    'SAO PEDRO': 'São Pedro',
    'SATURNINO AZEREDO': 'Saturnino Azeredo',
    'SB-10': 'SB-10',
    'SB-2': 'SB-2',
    'SB-3': 'SB-3',
    'SB-4': 'SB-4',
    'SB-5': 'SB-5',
    'SB-6': 'SB-6',
    'SB-7': 'SB-7',
    'SB-7A': 'SB-7A',
    'SB-8': 'SB-8',
    'SB-9': 'SB-9',
    'SEBASTIAO GODOY': 'Sebastião Godoy',
    'SENADOR HERMENEGILDO DE MORAIS': 'Senador Hermenegildo de Morais',
    'SERGIPE': 'Sergipe',
    'SIENA': 'Siena',
    'SILVIO ROMANO DE MELO': 'Sílvio Romano de Melo',
    'SOLDADO PM ADONAI DO CARMO OLIVEIRA': 'Soldado PM Adonai do Carmo Oliveira',
    'SPEZZIA': 'Spezzia',
    'SUCUPIRA': 'Sucupira',
    'TARENTO': 'Tarento',
    'TEREZA DE FREITAS FELTER': 'Tereza de Freitas Felter',
    'TESSALIA': 'Tessália',
    'TIRADENTES': 'Tiradentes',
    'TRIPOLI': 'Tripoli',
    'TURIM': 'Turim',
    'UVAIA': 'Uvaia',
    'VC-1': 'VC-1',
    'VC-10': 'VC-10',
    'VC-11': 'VC-11',
    'VC-12': 'VC-12',
    'VC-13': 'VC-13',
    'VC-14': 'VC-14',
    'VC-14A': 'VC-14A',
    'VC-15': 'VC-15',
    'VC-15A': 'VC-15A',
    'VC-16': 'VC-16',
    'VC-16A': 'VC-16A',
    'VC-17': 'VC-17',
    'VC-17A': 'VC-17A',
    'VC-18': 'VC-18',
    'VC-2': 'VC-2',
    'VC-3': 'VC-3',
    'VC-4': 'VC-4',
    'VC-5': 'VC-5',
    'VC-6': 'VC-6',
    'VC-7': 'VC-7',
    'VC-8': 'VC-8',
    'VC-9': 'VC-9',
    'VERA CRUZ': 'Vera Cruz',
    'VEREADOR ANTONIO DA LUCINDA': 'Vereador Antonio da Lucinda',
    'VEREADOR LUIZ SANTIAGO': 'Vereador Luiz Santiago',
    'VERONA': 'Verona',
    'VERONA I': 'Verona I',
    'VERONA II': 'Verona II',
    'VIA PERIMETRAL 1': 'Via Perimetral 1',
    'VIA PERIMETRAL 2': 'Via Perimetral 2',
    'VIA PRIMARIA 1': 'Via Primária 1',
    'VIA PRIMARIA 2': 'Via Primária 2',
    'VITORIA DA PAIXAO A BARBOSA': 'Vitória da Paixão A Barbosa',
    'WN': 'WN',
    'X': 'X',
    'Z': 'Z',
}

BAIRROS = {
    'AREA RURAL DE MORRINHOS': 'Área Rural de Morrinhos',
    'BARRA DO CORDEIRO': 'Barra do Cordeiro',
    'CENTRO': 'Centro',
    'CONDOMINIO RECANTO DAS ARARAS': 'Condomínio Recanto das Araras',
    'CONJUNTO HABITACIONAL MONTE VERDE': 'Conjunto Habitacional Monte Verde',
    'CRISTINA PARK': 'Cristina Park',
    'CRISTINA PARK 2': 'Cristina Park 2',
    'DESMEMBRAMENTO DOUTOR ADEDIMAS': 'Desmembramento Doutor Adedimas',
    'DESMEMBRAMENTO FERNANDO AZZI TEIXEIRA': 'Desmembramento Fernando Azzi Teixeira',
    'DESMEMBRAMENTO ZEZE ROMANO': 'Desmembramento Zezé Romano',
    'DISTRITO AGROINDUSTRIAL DE MORRINHOS': 'Distrito Agroindustrial de Morrinhos',
    'GENOVEVA ALVES': 'Genoveva Alves',
    'JARDIM AMERICA': 'Jardim América',
    'JARDIM BELA VISTA': 'Jardim Bela Vista',
    'JARDIM BELA VISTA II': 'Jardim Bela Vista II',
    'JARDIM BELA VISTA III': 'Jardim Bela Vista III',
    'JARDIM BELA VISTA IV': 'Jardim Bela Vista IV',
    'JARDIM COLIBRI': 'Jardim Colibri',
    'JARDIM GOIAS': 'Jardim Goiás',
    'JARDIM HELENA': 'Jardim Helena',
    'JARDIM MARIA ESTELA': 'Jardim Maria Estela',
    'JARDIM MARIA FERREIRA DE SOUZA': 'Jardim Maria Ferreira de Souza',
    'JARDIM PORTUGAL': 'Jardim Portugal',
    'JARDIM PRIMAVERA': 'Jardim Primavera',
    'JARDIM RENASCER': 'Jardim Renascer',
    'JARDIM ROMANO': 'Jardim Romano',
    'JARDIM ROMANO II': 'Jardim Romano II',
    'JARDIM SANTA FE': 'Jardim Santa Fé',
    'JARDIM SANTA TEREZINHA I': 'Jardim Santa Terezinha I',
    'JARDIM SANTA TEREZINHA II': 'Jardim Santa Terezinha II',
    'JARDIM SANTA TEREZINHA III': 'Jardim Santa Terezinha III',
    'JARDIM VENEZUELA': 'Jardim Venezuela',
    'JARDIM VERA CRUZ': 'Jardim Vera Cruz',
    'JK': 'JK',
    'LOTEAMENTO VINICIUS CANDIDO': 'Loteamento Vinícius Cândido',
    'MORRO DA SAUDADE I': 'Morro da Saudade I',
    'MORRO DA SAUDADE II': 'Morro da Saudade II',
    'PARQUE DAS LARANJEIRAS': 'Parque das Laranjeiras',
    'RESERVA ATENAS': 'Reserva Atenas',
    'RESIDENCIAL ALDEIA': 'Residencial Aldeia',
    'RESIDENCIAL ANTONIO CORREIA BUENO': 'Residencial Antônio Correia Bueno',
    'RESIDENCIAL CALIFORNIA': 'Residencial Califórnia',
    'RESIDENCIAL DARCY CHAVES': 'Residencial Darcy Chaves',
    'RESIDENCIAL DONA ONDINA': 'Residencial Dona Ondina',
    'RESIDENCIAL DOS BURITIS': 'Residencial dos Buritis',
    'RESIDENCIAL DOS IPES': 'Residencial dos Ipês',
    'RESIDENCIAL HERCILIO GOMES DE MELO': 'Residencial Hercílio Gomes de Melo',
    'RESIDENCIAL JARINA PARK': 'Residencial Jarina Park',
    'RESIDENCIAL MIRANTE DO BOSQUE': 'Residencial Mirante do Bosque',
    'RESIDENCIAL PORTAL DO LAGO': 'Residencial Portal do Lago',
    'RESIDENCIAL SANTA TEREZINHA': 'Residencial Santa Terezinha',
    'RESIDENCIAL VALERIA REIS': 'Residencial Valéria Reis',
    'SAO FRANCISCO': 'São Francisco',
    'SETOR AEROPORTO': 'Setor Aeroporto',
    'SETOR AEROPORTO II': 'Setor Aeroporto II',
    'SETOR AEROPORTO III': 'Setor Aeroporto III',
    'SETOR ARCA DE NOE': 'Setor Arca de Noé',
    'SETOR CARMEM LUCIA': 'Setor Carmem Lúcia',
    'SETOR CRISTINA': 'Setor Cristina',
    'SETOR CRISTO REDENTOR': 'Setor Cristo Redentor',
    'SETOR CRISTO REDENTOR - II ETAPA': 'Setor Cristo Redentor - II Etapa',
    'SETOR FELICIO CHAVES': 'Setor Felício Chaves',
    'SETOR IRINEIA DE FREITAS': 'Setor Irinéia de Freitas',
    'SETOR JOSE JESUINO FILHO': 'Setor José Jesuíno Filho',
    'SETOR LESTE UNIVERSITARIO': 'Setor Leste Universitário',
    'SETOR NOROESTE': 'Setor Noroeste',
    'SETOR OESTE': 'Setor Oeste',
    'SETOR PROFESSOR OLYNTHO CANDIDO': 'Setor Professor Olyntho Cândido',
    'SETOR SAO PEDRO': 'Setor São Pedro',
    'SETOR SEBASTIAO TELEZIO CARNEIRO DE ANDRADE': 'Setor Sebastião Telézio Carneiro de Andrade',
    'SETOR SOLAR DO BOSQUE': 'Setor Solar do Bosque',
    'SETOR SUL DOS POMARES': 'Setor Sul dos Pomares',
    'SOL NASCENTE': 'Sol Nascente',
    'VILA BELA': 'Vila Bela',
    'VILA MUTIRAO': 'Vila Mutirão',
    'VILA NOSSA SENHORA DO CARMO': 'Vila Nossa Senhora do Carmo',
    'VILA NOVA': 'Vila Nova',
    'VILA SANTOS DUMONT': 'Vila Santos Dumont',
}
